[tool.setuptools]
packages = ["geth"]
package-dir = {"" = "."}

[tool.setuptools.package-data]
geth = ["*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "geth"
version = "0.1.0"